version: '2.1'
orbs:
 orb-tools: circleci/orb-tools@11.1
 k6io: k6io/test@1.2.3

filters: &filters

workflows:
  load_test:
    jobs:
      - k6io/test:
          script: tests/world-payments.js
      - opb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: k6io/test@1.2.3
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
           - orb-tools/pack
           - k6io/test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
