version: '2.1'
orbs:
 penetron1: btt_namespace/penetron1@dev:<<pipeline.git.revision>>
 k6io: k6io/test@1.1.0
workflows:
  load_test:
    jobs:
      - k6io/test:
          script: tests/world-payments.js
      - k6io/publish:
          orb-name: btt_namespace/penetron1
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - k6io/test
          context: orb-publishing

